# spec/e2e/nodesets/Dockerfile.el8
FROM almalinux:8

RUN yum install -y dnf-utils && \
    dnf config-manager --set-enabled powertools && \
    yum install -y wget which cronie iproute initscripts langpacks-en glibc-all-langpacks && \
    yum install -y epel-release && \
    dnf -y module enable ruby:3.3 && \
    dnf -y module enable nodejs:20 && \
    yum install -y https://yum.osc.edu/ondemand/latest/ondemand-release-web-4.0-1.el8.noarch.rpm && \
    sed -i 's|ondemand/4.0/web|ondemand/build/4.0/web|g' /etc/yum.repos.d/ondemand-web.repo && \
    dnf config-manager --save --setopt ondemand-web.exclude='ondemand ondemand-gems* ondemand-selinux' && \
    yum install -y ondemand ondemand-dex ondemand-selinux && \
    yum install -y python3 python3-pip && \
    python3 -m pip install flask && \
    yum clean all
